### ISSUE TITLE
Frete na página do produto

### ISSUE THREAD

**Issue by vissoci** [FrenetGatewaydeFretes/frenet_magento#10]
Alguma possibilidade de incluírem essa funcionalidade?

**Comment by rafaelmancini** [comment]
Olá, em princípio nosso módulo não altera nada de frontend para ser compatível com qualquer tema e etc. Recomendamos instalar módulos específicos para isso. Veja essa dica: http://referenciamagento.blogspot.com/2013/06/frete-na-pagina-do-produto.html

**Comment by vissoci** [comment]
Obrigado @rafaelmancini 
Sim, o módulo de vocês é excelente e faz muito sentido continuar dessa forma, pois funciona como um reloginho.
