### ISSUE TITLE
Alterar Logs

### ISSUE THREAD

**Issue by almirsantos99** [FrenetGatewaydeFretes/frenet_magento#11]
Por favor alterem o local dos logs e retirem do System.log pois existe lojas nossas atingindo 10gb de system.log em 2 meses, ai se ocorrer algum erro no system.log não conseguimos verificar por conta disso.
Basta alterar a função de log do observer e o akhilleus.php de 
Mage::log('Akhilleus: ' . $msg);
para
Mage::log('Akhilleus: ' . $msg, null, 'frenet.log', 1);

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
