### ISSUE TITLE
Não calcula para tipo de produto personalizado

### ISSUE THREAD

**Issue by redati** [FrenetGatewaydeFretes/frenet_magento#12]
Tenho um tipo de produto personalizado "Milople Personalized Product" e apenas para esse tipo de produto o frete não calcular. 

No log o $productsCount = count ($this->_simpleProducts); retorna 0, ou seja, não pega esse tipo de produto, parece pegar apenas produtos simples.

Qual adaptação devo fazer para calcular o "Milople Personalized Product" ?

**Comment by redati** [comment]
Consegui, vou deixar aqui, caso alguém precise.
Alterei 

if (strcmp ($type_id, 'simple') ) {
                $this->_log("continue " . $product->getTypeId());
                continue;
            }
 para 

if (strcmp ($type_id, 'simple') && $type_id != 'personalized' ) {
                $this->_log("continue " . $product->getTypeId());
                continue;
            }


em Akhilleus.php

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
