### ISSUE TITLE
Dúvidas? 

### ISSUE THREAD

**Issue by lucasfpiovesan12** [FrenetGatewaydeFretes/frenet_magento#15]
Esse módulo será descontinuado ou já foi? kkk

**Comment by ivanaugustobd** [comment]
Me deparei com essa questão hoje também. Aparentemente tem um novo repo (atualizado esse ano mesmo): https://github.com/FrenetGatewaydeFretes/frenet-magento

Fonte: https://ajuda.frenet.com.br/s/article/configuracao-novo-modulo-magento

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
