### ISSUE TITLE
Não foi possível calcular o frete, consulte os dados informados.

### ISSUE THREAD

**Issue by raphaloi** [FrenetGatewaydeFretes/frenet_magento#2]
Olá! Fiz a instalação do módulo, a integração de acordo com o tutorial.. mas em meu site consta essa mensagem ao tentar finalizar um pedido: 

Não foi possível calcular o frete, consulte os dados informados.

**Comment by cfgalvani** [comment]
@raphaloi você resolveu o problema? Estou com esse problema com alguns clientes apenas. Acabei de abrir um ticket lá com o pessoal da Frenet.

**Comment by raphaloi** [comment]
@cfgalvani eu consegui resolver o problema alterando um arquivo do checkout da magento. 

Substitui o local onde o módulo faz a busca do cep (sistema dos correios, o qual apresenta inúmeras instabilidades e picos) por este aqui: https://viacep.com.br/

Não esqueça de configurar de acordo com o webservice que vc usa, por exemplo:

viacep.com.br/ws/01001000/xml/

**Comment by cfgalvani** [comment]
@raphaloi eu uso o viacep também. O pessoal do suporte já respondeu aqui e deu certo. Haviam produtos cadastrados como kilogramas, mas estou enviando as informações como gramas.. O peso somado dava menos que 1 grama no final das contas. Obrigado!

**Comment by raphaloi** [comment]
César eu consegui resolver o problema alterando um arquivo do checkout da magento.

Substitui o local onde o módulo faz a busca do cep (sistema dos correios, o qual apresenta inúmeras instabilidades e picos) por este aqui: https://viacep.com.br/

Não esqueça de configurar de acordo com o webservice que vc usa, por exemplo:

viacep.com.br/ws/01001000/xml/ https://viacep.com.br/ws/01001000/json/

---

De: César Felipe Leite Galvani notifications@github.com
Enviado: terça-feira, 25 de outubro de 2016 14:35
Para: FrenetGatewaydeFretes/frenet_magento
Cc: raphaloi; Mention
Assunto: Re: [FrenetGatewaydeFretes/frenet_magento] Não foi possível calcular o frete, consulte os dados informados. (#2)

@raphaloihttps://github.com/raphaloi você resolveu o problema? Estou com esse problema com alguns clientes apenas. Acabei de abrir um ticket lá com o pessoal da Frenet.

##

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
