### ISSUE TITLE
Erro no XML

### ISSUE THREAD

**Issue by albertobraschi** [FrenetGatewaydeFretes/frenet_magento#3]
Magento versão. 1.9.2.3 

Akhilleus: Country ID BR
akhilleus [241]: URL Error - Server was unable to read request. ---> There is an error in XML document (2, 533). ---> Input string was not in a correct format. request <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:GetShippingQuote><ns1:quoteRequest><ns1:Username>NONE</ns1:Username><ns1:Password>NONE</ns1:Password><ns1:SellerCEP>00000000</ns1:SellerCEP><ns1:RecipientCEP>00000000</ns1:RecipientCEP><ns1:RecipientDocument></ns1:RecipientDocument><ns1:ShipmentInvoiceValue>20.02</ns1:ShipmentInvoiceValue><ns1:ShippingItemArray><ns1:ShippingItem><ns1:Weight>1.0000</ns1:Weight><ns1:Length></ns1:Length><ns1:Height></ns1:Height><ns1:Width></ns1:Width><ns1:Diameter>0</ns1:Diameter><ns1:SKU>999</ns1:SKU><ns1:Category></ns1:Category><ns1:isFragile>false</ns1:isFragile></ns1:ShippingItem><ns1:ShippingItem><ns1:Weight>0.0150</ns1:Weight><ns1:Length></ns1:Length><ns1:Height></ns1:Height><ns1:Width></ns1:Width><ns1:Diameter>0</ns1:Diameter><ns1:SKU>78-44x4</ns1:SKU><ns1:Category>Root Catalog|Default Category|Estética Automotiva|Promoções|Acessórios|Marcas|Aplicador|Lake Country|</ns1:Category><ns1:isFragile>false</ns1:isFragile></ns1:ShippingItem></ns1:ShippingItemArray><ns1:RecipientCountry>BR</ns1:RecipientCountry></ns1:quoteRequest></ns1:GetShippingQuote></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by dubaggio** [comment]
Oi Alberto,

O problema está aqui: 
<ns1:Length></ns1:Length> 
<ns1:Height></ns1:Height> 
<ns1:Width></ns1:Width>

O produto está sem nenhuma dimensão cadastrada. Você tem duas opções, habilitar a opção "Utilizar dimensões padrão" (Neste caso, você precisará preencher os campos altura, largura e comprimento padrão que estão na configuração do módulo em sua loja) ou então editar o produto incluindo as dimensões (altura, largura e comprimento).

Para um melhor atendimento, quando precisar de suporte recomendo que você envie um ticket através deste link: https://frenet.zendesk.com/hc/pt-br/requests/new
