### ISSUE TITLE
leadtime não é somado no prazo

### ISSUE THREAD

**Issue by rebecapf** [FrenetGatewaydeFretes/frenet_magento#6]
Olá!
Mesmo colocando os dias a mais no cadastro do produto, o cálculo do prazo não muda... 
Alguma ideia do que pode ser?

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
