### ISSUE TITLE
Cupom de frete grátis não funciona com frenet

### ISSUE THREAD

**Issue by davirs** [FrenetGatewaydeFretes/frenet_magento#7]
Olá! Cupons de destonto para frete grátis ou qualquer outra regra de desconto para valor de frete interno do magento não funcionam com o módulo frenet.
Eu sei que da pra configurar muita coisa dentro do painel da frenet mas pelo menos cupom de frete grátis é extremamente necessário..

**Comment by ThiagoSantos01** [comment]
Mesmo problema no magento2, isso será resolvido?

**Comment by crwa** [comment]
Pessoal, alguma novidade sobre isso ? Tenho o Frenet e regras de cupom para frete grátis não funcionam ainda. Eu vi que pelo painel da frenet através do upgrade do plano por lá existe a possibilidade de configurar cupoms, mas o magento me dá essa possibilidade então quero resolver pela minha loja, sem precisar alterar planos de serviço com a Frenet.

**Comment by rafaelmancini** [comment]
Olá pessoal, é possível utilizar cupom de frete associado à regra de frete na Frenet. Veja este artigo: http://ajuda.frenet.com.br/pt-BR/articles/2453089-regra-de-cupom-de-desconto
Caso você queria usar cupons de frete grátis desconectado das regras de frete da Frenet, você pode associar esse cupom à uma outra forma de entrega nativa da plataforma, por exemplo o Free Shipping method.
