### ISSUE TITLE
Campos obrigatórios nos produtos que não tinham antes.

### ISSUE THREAD

**Issue by elsondinardo** [FrenetGatewaydeFretes/frenet_magento#8]
Olá pessoal,

Estou utilizando o módulo de frete de vocês mas depois disso tenho campos obrigatórios a serem preenchidos nos produtos que não tinham antes. Os campos são:

Comprimento (cm)* 
Altura (cm)* 
Largura (cm)* 
Lead time (dias)*

Eu estava utilizando anteriormente o modulo do Pedro Teixeira e parei de usar pois não funciona mais com a atual mudança dos códigos dos correios. Mas o módulo dele não exigia esses campos obrigatórios. Como eu faço com o módulo de vocês para não precisar informar os tamanhos em cada produto que abro? Veja bem, todos os produtos em minha loja (são muitos produtos) não tem essa informação, o campo é em branco... No caso se eu abro um prdouto pra fazer qualquer alteração e clico em salvar, esses campos obrigatórios não deixam eu salvar o produto sem serem preenchidos, o que não ocorria anteriormente.

Espero que possam me ajudar nessa. Obrigado.
![capturar](https://cloud.githubusercontent.com/assets/7572660/25862796/b46322c0-34bf-11e7-8072-f4921d8f864a.PNG)

**Comment by vissoci** [comment]
Veja se habilitando a dimensão padrão resolve.
Penso que se não estiver habilitado a lógica seria o sistema exigir as medida dos produtos.

**Comment by vissoci** [comment]
@elsondinardo Tive esse problema em uma loja recentemente. A solução para preencher tantos campos foi exportar a lista de produtos e arrumar no excel. Depois importar de volta para o Magento. 
**Não esqueça de fazer um backup antes de tentar isso!!!**

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
