### ISSUE TITLE
Mensagem de exibição cas não haja formas de entrega

### ISSUE THREAD

**Issue by uileprojecttus** [FrenetGatewaydeFretes/frenet_magento#9]
Boa tarde, 

Tenho alguns clientes que moram em áreas rurais ou que a localização é precária e não há formas de entrega para eles, ou até mesmo quando não há nenhum retorno nas formas de entrega (o que ocorre raramente).

Gostaria de exibir uma mensagem caso não haja este retorno, porém não tive sucesso. A Frenet disponibiliza algum campo que possamos adicionar em caso de não haver retorno de nenhum método de entrega?

**Comment by lucas-bernardes-frenet** [comment]
Olá, 
foram realizadas algumas alterações no módulo Frenet e este modulo https://github.com/FrenetGatewaydeFretes/frenet_magento foi descontinuado, este Github está sendo mantido por questões de compatibilidade de versões muito antigas do Magento.
Todas nossas implementações e melhorias estão sendo realizadas no módulo a seguir:
https://github.com/FrenetGatewaydeFretes/frenet-magento

Algumas implementações importantes foram desenvolvidas, pensando no melhor desempenho do módulo.
Como por exemplo, alteração do método de chamada da API de SOAP para REST.
Fizemos alteração da referência do módulo em todos nossos meios de comunicação e caso estejam utilizando este módulo obsoleto, por gentileza migrem para a nossa nova tecnologia.

Lembrem-se de testar em um ambiente de testes de sua loja antes de implantar em um ambiente produtivo.


Atenciosamente,
